### ISSUE TITLE
Size on disk as well as image size

### ISSUE THREAD

**Issue by lizrice** [microscaling/microbadger#1]
Suggested by @frol here: https://github.com/CenturyLinkLabs/imagelayers-graph/issues/85#issuecomment-236139010

**Comment by frol** [comment]
Thank you for taking care of the idea. I am eager to update my "0 MB" ImageLayer badges, so I will be waiting for this one.

**Comment by lizrice** [comment]
I don't think we are likely to find a good way to do this any time soon, so I'm going to close it.
