### ISSUE TITLE
Generating webhook URLs

### ISSUE THREAD

**Issue by rscohn2** [microscaling/microbadger#12]
I want to use the webhook to update the info for a large set of images. Is there a URL that only contains the repo name and not the stuff afterwards? It would be tedious to get the webhook URL from your web page for every image:

https://hooks.microbadger.com/images/rscohn2/idp2_core.ubuntu/KToFO4mXwId81ddvWhWdxivWAHU=

**Comment by rossf7** [comment]
Thanks for raising this but I'm afraid the webhook URLs do need the random suffix. This is so the URLs are not predictable and is pretty standard for webhooks. But I can see that getting the URLs for multiple images is a bit tedious.

A feature we should be adding soon is support for private images. This will require storing Docker login details. It may then be possible to get a list of your images from the Docker Registry API. We could then list your images along with the webhook URLs.

**Comment by rscohn2** [comment]
OK. Thanks.
