### ISSUE TITLE
Processing metadata too long

### ISSUE THREAD

**Issue by forumi0721** [microscaling/microbadger#14]
Hi,
I use microbadger in my docker images.

But one image cannot create badge.

Processing forumi0721archx64/arch-x64-dev metadata

Almost day..... Something wrong at create logic.
Please check this.

**Comment by rossf7** [comment]
Hi,
sorry something went wrong inspecting this image. I've just manually set it to be re-inspected and its now there. Thanks for using the badges!

**Comment by forumi0721** [comment]
Thanks, It works.
