### ISSUE TITLE
Better Notification Support 

### ISSUE THREAD

**Issue by vshank77** [microscaling/microbadger#18]
<img width="919" alt="screen shot 2017-01-06 at 14 58 54" src="https://cloud.githubusercontent.com/assets/191676/21721538/b3043d06-d420-11e6-83a2-972e262b7536.png">

We would appreciate if the notification was much better including the published version and labels support. We use the notifications as the release publishing mechanism for our product and the current thing does not tell anything to our customers about what changed.

**Comment by lizrice** [comment]
Hi @vshank77, thanks for raising this. 

The underlying JSON for the notification includes information about which tags have changed (see [this post](https://medium.com/microscaling-systems/what-are-change-notifications-379c428da5d7#.fzkehb9v9) for more info). Slack just shows the Text field and ignores the other information. 

Do the new_tags, changed_tags, deleted_tags give you what you need?

**Comment by vshank77** [comment]
Sorry @lizrice, missed the comment. The tags definitely give us what we need. Appreciated.
