### ISSUE TITLE
Support tags

### ISSUE THREAD

**Issue by atmoz** [microscaling/microbadger#2]
Looks like it's possible to select tags from a dropdown list, but the badge image url stays the same (and shows the "latest" tag).

Is this a bug or a missing feature?

**Comment by lizrice** [comment]
The idea is that you wouldn't need to update the badge - it would always show the 'latest' version (once we've refreshed the information, or straight away if you use the webhook to let us know that it has updated). 

It sounds as though you'd like to have badges for different tags - can you tell us a bit more about the use case?

**Comment by atmoz** [comment]
I have two types of tags that use two different kind of distributions: debian and alpine. I would love to add a badge on each line under "Supported tags ...", showing users the difference in size between debian and alpine, here: https://hub.docker.com/r/atmoz/sftp/

**Comment by JacobSanford** [comment]
+1 To this!

**Comment by rochdev** [comment]
+1

**Comment by rossf7** [comment]
The badge images now support tags in the URL e.g. https://images.microbadger.com/badges/image/atmoz/sftp:alpine.svg

[![](https://images.microbadger.com/badges/image/atmoz/sftp:alpine.svg)](https://microbadger.com/images/atmoz/sftp "Get your own image badge on microbadger.com")

For now you'll need to edit the Markdown to add the tag. Also the link to the site will show the metadata for the latest tag. To see the metadata for other tags you'll need to select them in the dropdown.

Website support for tags in the URL will be coming soon. I'll leave this issue open till then.

**Comment by atmoz** [comment]
Great! I've added badges to my images :+1:

**Comment by lizrice** [comment]
This is now supported in the UI too so it's easy to grab the badges for the tag you want
