### ISSUE TITLE
Can't see my public Docker Hub image

### ISSUE THREAD

**Issue by jsierles** [microscaling/microbadger#24]
https://hub.docker.com/r/nextjournal/ubuntu-language-base

This image is public, but I can't load it on the Microbadger site:

`nextjournal/ubuntu-language-base not found on Docker Hub`

**Comment by lizrice** [comment]
It's [available now](https://microbadger.com/images/nextjournal/ubuntu-language-base) so I'm closing this, but please re-open if you don't see it OK.
