### ISSUE TITLE
Page broken after webhook notification

### ISSUE THREAD

**Issue by rahulpowar** [microscaling/microbadger#26]
I added the labels as suggested and setup a webhook from DockerHub to update the badge. After the push the page is broken.

https://microbadger.com/images/redsift/dnstrace

**Comment by burgerdev** [comment]
I'm seeing the same error page for my project. I suspect that it was caused by me adding an invalid URL as VCS label.

```ini
# wrong (copy paste mistake)
org.label-schema.vcs-url="e.g. https://github.com/....."
# correct url
org.label-schema.vcs-url="https://github.com/....."
```

**Comment by lizrice** [comment]
@burgerdev that's exactly what the problem is, just putting together a fix

**Comment by rossf7** [comment]
Fix is deployed and the page for your image is now working. Sorry it took me a while to get this deployed.
