### ISSUE TITLE
Layer information not yet retrieved

### ISSUE THREAD

**Issue by sheringham** [microscaling/microbadger#27]
It only shows the layer numbers but not detailed layer information for my docker image esir/docker-efb. I have tried to google a solution but no luck. Please help to investigate, thanks.

**Comment by lizrice** [comment]
Hi @sheringham, I can see the layers so I expect it the processing just got queued for a while - please can you confirm whether you see them OK now?

**Comment by sheringham** [comment]
@lizrice yes, it is OK now. Thanks.
