### ISSUE TITLE
Can't view CS50's ide-offline's labels

### ISSUE THREAD

**Issue by vharsh** [microscaling/microbadger#28]
I cannot view CS50 [ide-offline](https://hub.docker.com/r/cs50/ide50-offline/)'s labels. The website says it [wasn't found](https://microbadger.com/images/cs50/ide50-offline).
> Is it because the Dockerfile is private?

**Comment by lizrice** [comment]
Yes, you will need to enter your Docker Hub credentials for MicroBadger to be able to access a private image. 

I'll close for now assuming that is the issue, but please reopen if you still can't get the image details.
