### ISSUE TITLE
Shows 0 Byte, on my multi stage image.

### ISSUE THREAD

**Issue by medyagh** [microscaling/microbadger#29]
my image is  15.3 MB but the micro badger shows it as 0 bytes and 7 layers.

https://microbadger.com/images/k8guard/k8guard-report

and also says "layer information not yet retrieved"
I also setup the webhook so each time it gets built in docker hub to call microbadger, but that didnt help to fix it.

could it be because I am using multi stage docker file build ?
here is my dockerfile
https://github.com/k8guard/k8guard-report/blob/master/Dockerfile

**Comment by lizrice** [comment]
I think this is simply that MicroBadger hadn't had time to inspect the image yet - it can take a while to get the layer information especially if we have a lot of images queued up. It's now showing as a download size of 6.6MB and the layer details are there. I'll close now but please reopen if you're still seeing problem.

**Comment by dinuta** [comment]
Same issue here:

https://microbadger.com/images/dinutac/jinja2docker

**Comment by rossf7** [comment]
Sometimes the initial inspection doesn't work first time.

The layers are now there. I used the webhook to trigger it to be inspected again. You just need to login via GitHub to get the webhook URL.

```bash
curl -X POST https://hooks.microbadger.com/images/dinutac/jinja2docker/HoUtwZApR7v7kLfjM92T75HDcmM=
```

microbadger is a free service that we run in our spare time. This means we have limited time available for bug fixing.

**Comment by dinuta** [comment]
Thanks Ross. Speaking in general the badges **must** work because the people rely on them :)
Anyway thanks for your fast response. You rock!

**Comment by rossf7** [comment]
Hey @dinuta, thanks that's great I'm glad I could help.

> badges must work because the people rely on them

Sorry to be pedantic but we offer no SLO for microbadger. It's a best efforts service because we operate it as a side project. If you need very high uptime for badges I would suggest using another service.
