### ISSUE TITLE
No layer information is shown for Official Library Images

### ISSUE THREAD

**Issue by ruffsl** [microscaling/microbadger#30]
For over a year, I have never seen layer information for our official docker hub image.
A year or more ago, I remember it was working, but for the last year it stopped reporting layers size, etc:
https://microbadger.com/images/library/ros
> Layer information not yet retrieved

Perhaps you could look into internally, perhaps reset it's cache?

**Comment by zcalusic** [comment]
I have the same problem, sometimes layer information refreshes, many times not.

Is this project abandoned?

**Comment by jasonmp85** [comment]
Possibly. Why can't any of these things stay alive?

**Comment by lizrice** [comment]
It's not abandoned, but day jobs mean we have not been able to spend much time on it. I think I've got a fix for this now though (or at least for one possible cause) so bear with us while we test it and get it out.

**Comment by smiller171** [comment]
Any movement on this @lizrice ? If you need a hand I might be able to take a look

**Comment by lizrice** [comment]
Yes I think this is now fixed (https://microbadger.com/images/ros has size & layer info at the moment at least!)  I'm going to close this for now but please do feel free to reopen or raise a new issue if you see this again
