### ISSUE TITLE
Infinite processing meta

### ISSUE THREAD

**Issue by forumi0721** [microscaling/microbadger#33]
hi
I use microbadger many repository.
But 1 repo cannot finish processing.

What's the wrong?

https://microbadger.com/images/forumi0721archx64build/arch-x64-dev-android

**Comment by rossf7** [comment]
Hi,
your image has now been processed. 

We had a problem with the overnight refresh process that updates the image metadata. This meant new images were not being processed. Still investigating the cause of the overnight refresh problem but I'm going to close this.

Thanks for reporting the problem!

**Comment by dennybaa** [comment]
Same issue and it is constantly reoccurring.  Why?

**Comment by dennybaa** [comment]
This is always happens :((((
![](https://i.gyazo.com/1361417508287522f577bc8ca3e41900.png)

with one or another repo. Micro-badger does not work stable, what does these issues cause?
