### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by SkYNewZ** [microscaling/microbadger#34]
Hi! I push an image on the Docker Hub (https://hub.docker.com/r/skynewz/cr3dov3r) at 6pm and I can't see it on Microbadger. Can you help me please ? Otherwise, I can see all my other image

**Comment by rossf7** [comment]
Hi, your image is fixed now. There was a backlog in one of our inspection queues which meant the layers and sizes hadn't been processed.

**Comment by SkYNewZ** [comment]
Hi! Thank a lot for fixing this. Have a good day!
