### ISSUE TITLE
Layer information not being retrieved

### ISSUE THREAD

**Issue by accetto** [microscaling/microbadger#35]
Hello

It worked yesterday, but today it does not with [this](https://hub.docker.com/r/accetto/ubuntu-vnc-xfce-firefox/) and any other image in this [repository](https://hub.docker.com/u/accetto/). 

Is there anything I should do or should I simply wait?
Does it require yout intervention or does it recover itself?

Thanks

**Comment by rossf7** [comment]
Hi,
your images have layer information now. There was a backlog in our queue that processes the layer information. We have a fix for that which should be ready soon and will help the situtation.

To fix the problem yourself you can get the webhook URL from the site and make a POST request. This will repeat the inspection process. If the layer information still isn't displayed then there is probably a backlog in the queue. It will get cleared eventually so I'd recommend trying again later.

Thanks for reporting this and sorry for the inconvenience.

Cheers

Ross

**Comment by accetto** [comment]
Hi Ross,

thanks a lot for the promp solution, it's working again. :+1: 
And I wish you a happy New Year!

Cheers
accetto

**Comment by rossf7** [comment]
You're welcome 😄  Happy New Year!
