### ISSUE TITLE
No layer info after rebuild even having web hooks

### ISSUE THREAD

**Issue by accetto** [microscaling/microbadger#36]
Hello,

there is no layer info after rebuild again. The existing web hooks worked correctly about two days ago. Could you please check the accetto's repositories again? Thanks a lot.

Cheers
accetto

**Comment by rossf7** [comment]
Hi @accetto 
sorry, there was a backlog in our inspection queue which meant webhooks weren't being processed.

It's cleared now and I checked your images and they have layers. Closing this but please reopen if you still have problems.

Thanks

Ross
