### ISSUE TITLE
Available image still "not found on Docker Hub"

### ISSUE THREAD

**Issue by relistan** [microscaling/microbadger#37]
I'm trying to get badges for https://hub.docker.com/r/gonitro/envoy-ui/, which exists, but https://microbadger.com/images/gonitro/envoy-ui incorrectly returns `gonitro/envoy-ui not found on Docker Hub` .

**Comment by relistan** [comment]
![screen shot 2018-05-02 at 2 01 17 pm](https://user-images.githubusercontent.com/267761/39524600-5c7b5fd4-4e11-11e8-9e36-84bd7bd91c73.png)
![screen shot 2018-05-02 at 2 02 11 pm](https://user-images.githubusercontent.com/267761/39524626-715d194c-4e11-11e8-9943-f261313313fa.png)

**Comment by iranzo** [comment]
Same here with <https://microbadger.com/images/citellus/citellus>

**Comment by relistan** [comment]
Awesome, thanks @rossf7 !

**Comment by relistan** [comment]
Looks like it's all back to normal for my repo and the one linked by @iranzo . Cheers

**Comment by rossf7** [comment]
You're welcome! It was a problem with the worker nodes and replacing them fixed it.

**Comment by iranzo** [comment]
Great! thanks a lot!

**Comment by nkprince007** [comment]
Same here. 

Dockerhub URL: https://hub.docker.com/r/viperdev/thumbor-s3/
Microbadger URL: https://microbadger.com/images/viperdev/thumbor-s3
