### ISSUE TITLE
Images reference ImageLayers.io

### ISSUE THREAD

**Issue by jimschubert** [microscaling/microbadger#4]
I see this on my metadata page: https://microbadger.com/#/images/jimschubert/8-jdk-alpine-mvn

![image](https://cloud.githubusercontent.com/assets/109659/17558581/1505fe02-5ee9-11e6-9aea-eb27d5dbd134.png)

These images look like they were pulled from ImageLayers.io. The left circled image references a commit badge, which isn't available in the badges selection just above where the screenshot was taken.  Navigating to the location the commit batch _would_ be (https://images.microbadger.com/badges/commit/jimschubert/8-jdk-alpine-mvn.svg) there's no commit hash.

**Comment by lizrice** [comment]
The badges we're generating do look like the imagelayers ones, yes. They're intended to be a drop-in replacement as the imagelayers ones are not compatible with V2 of the Docker Registry API. 

To get the source code badge there needs to be a label built into the image that indicates the commit ref. There is more info about labelling images here: https://microbadger.com/#/labels
