### ISSUE TITLE
Expired certificate for microbadger.com

### ISSUE THREAD

**Issue by joschi** [microscaling/microbadger#41]
The certificate for https://microbadger.com/ expired on 2018-07-03T12:00:00Z.

```text
$ echo | openssl s_client -servername microbadger.com -connect microbadger.com:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Jun  3 00:00:00 2017 GMT
notAfter=Jul  3 12:00:00 2018 GMT
```

**Comment by rossf7** [comment]
@joschi Thanks so much for reporting this to us! This is now fixed.

We use ACM from AWS so the renewal should be automated. But there was a problem with the cert config. The cert had alt names for some other domains that we've migrated to Ingresses and Let's Encrypt so it wasn't renewed.

I've created a new ACM certificate with just the relevant domains. So the automated renewal should work in future.

**Comment by joschi** [comment]
@rossf7 Awesome, thanks!
