### ISSUE TITLE
Image not found on DockerHub

### ISSUE THREAD

**Issue by nkprince007** [microscaling/microbadger#43]
The image exists on docker hub but isn't being shown on micro badger.

Dockerhub URL: https://hub.docker.com/r/viperdev/thumbor-s3/
Microbadger URL: https://microbadger.com/images/viperdev/thumbor-s3

**Comment by rossf7** [comment]
Hi @nkprince007 your image is appearing now. Sorry for the inconvenience.

It's likely there was a problem fetching the metadata from Docker Hub. We have an automated refresh that usually fixes this but in this case I needed to refresh manually.

**Comment by 19majkel94** [comment]
@nkprince007 	
The same problem with another image:
https://microbadger.com/images/pkosiec/mongo-seeding
https://hub.docker.com/r/pkosiec/mongo-seeding/

**Comment by greatfireball** [comment]
@nkprince007 
Same problem for 
https://microbadger.com/images/greatfireball/ime_deseq2 https://hub.docker.com/r/greatfireball/ime_deseq2/
