### ISSUE TITLE
stuck on fetch metadata

### ISSUE THREAD

**Issue by gengjiawen** [microscaling/microbadger#47]
see https://microbadger.com/images/reactnativecommunity/react-native-android

**Comment by lizrice** [comment]
Thanks for reporting - this is showing up again now

**Comment by gengjiawen** [comment]
Thanks.

**Comment by gengjiawen** [comment]
@lizrice Looks like the image size is still 0 byte after a few days.

**Comment by rossf7** [comment]
@gengjiawen Size information is there now. There was a backlog in the queue that does the layer inspection.

**Comment by gengjiawen** [comment]
@rossf7 @lizrice The size are not showing again, can you check this ? Thanks.
