### ISSUE TITLE
Microbadger cannot find image while it does exist

### ISSUE THREAD

**Issue by jgeusebroek** [microscaling/microbadger#48]
Not sure if this is the correct place to raise this issue, let me know if I need to report this issue elsewhere. The image absolutely, positively, exists :)

<img width="757" alt="screen shot 2018-12-04 at 19 32 14" src="https://user-images.githubusercontent.com/203215/49464570-8846e680-f7fb-11e8-806b-0e5e05a6d763.png">

**Comment by lizrice** [comment]
We gave Microbadger a kick and you image is there now - thanks for reporting this!
