### ISSUE TITLE
Image not found on Docker Hub

### ISSUE THREAD

**Issue by forwardcomputers** [microscaling/microbadger#52]
I am having some issues with my docker image https://hub.docker.com/r/forwardcomputers/audacity which exists, but https://microbadger.com/images/forwardcomputers/audacity incorrectly returns "forwardcomputers/audacity not found on Docker Hub"

**Comment by rossf7** [comment]
Hi @forwardcomputers sorry about the delayed response but your image is appearing on MicroBadger.

We sometimes have problems retrieving metadata from Docker Hub. We do daily and weekly refreshes and on a subsequent attempt this succeeded.
