### ISSUE TITLE
microbadger.com down?

### ISSUE THREAD

**Issue by crazy-max** [microscaling/microbadger#59]
MicroBadger [looks down](https://downforeveryoneorjustme.com/microbadger.com) from here.

**Comment by davidkarlsen** [comment]
```
dig microbadger.com @1.1.1.1

; <<>> DiG 9.10.6 <<>> microbadger.com @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 32538
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;microbadger.com.               IN      A

;; Query time: 725 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Wed May 01 15:56:00 CEST 2019
;; MSG SIZE  rcvd: 44
```

**Comment by SuperSandro2000** [comment]
Seems like we have no DNS entry.

**Comment by rossf7** [comment]
Thanks for reporting. Yes looks like the problem is DNS. We're investigating we'll update when we have more news.

**Comment by rossf7** [comment]
We had a billing problem with our AWS account and it was suspended. The problem is resolved but there is a delay while AWS restore our account. Sorry for the inconvenience and thanks again for reporting.

We'll update when we have more news.

**Comment by rossf7** [comment]
Restore is complete and the site is back up. Thanks for bearing with us!

Closing this but please open another issue if you still have problems.

**Comment by crazy-max** [comment]
LGTM thx!
