### ISSUE TITLE
microbadger API down

### ISSUE THREAD

**Issue by chris48s** [microscaling/microbadger#60]
https://api.microbadger.com/ and all API calls throw a 404

```
$ curl -I https://api.microbadger.com/
HTTP/2 404 
server: nginx/1.13.12
date: Wed, 08 May 2019 20:02:49 GMT
content-type: text/plain; charset=utf-8
content-length: 19
x-content-type-options: nosniff
strict-transport-security: max-age=15724800; includeSubDomains
```

**Comment by lenovouser** [comment]
I think they just changed their API?

[`api.microbadger.com/v1/images/alpine`](https://api.microbadger.com/v1/images/alpine) and [`api.microbadger.com/v1/images/fedora/apache`](https://api.microbadger.com/v1/images/fedora/apache) work for example.

**Comment by chris48s** [comment]
stand down

Turns out the API works just great.. if you call endpoints that actually exist :man_facepalming:
