### ISSUE TITLE
Latest tags are not showing up 

### ISSUE THREAD

**Issue by amir20** [microscaling/microbadger#62]
Hello there. I created a docker image called [Dozzle](https://hub.docker.com/r/amir20/dozzle/). Most recent version is `1.10.3`. I have also added labels to update the version number. I noticed that microbadger is not  picking up the [latest version](https://microbadger.com/images/amir20/dozzle) even after it has attempted to update. 

This might be a bug? I am trying to figure web hooks and see if that fixes it.

**Comment by rossf7** [comment]
Hey @amir20,
I'm sorry this isn't working. Yes it's always worth trying the webhook and we need better docs there.
I just called it myself.

To use the webhook you need to log in via GitHub and then go back to your image page and click the "Get the webhook" button on the right nav.

You need to make a POST request using `curl` or you could use something like the Postman Chrome extension.

```
curl -X POST https://hooks.microbadger.com/images/...
```

Let me know if calling the webhook doesn't fix it. We also recommend using the webhook support in Docker Hub. So we re-inspect your image whenever you push a new tag.

**Comment by amir20** [comment]
I have added the microbadger hook with docker hub. It seems to be working as of now. But most recently I had a minor version bump. Before I only had patches. I'll close for now and reopen if it doesn't work. 

Thanks for the quick response!

**Comment by darribas** [comment]
Sorry I have the same problem with [`darribas/gds`](https://github.com/darribas/gds_env), could you please point to any documentation page on how to set up the webhook and make the POST request? Thank you very much!

**Comment by darribas** [comment]
Sorry, re-read more carefully and it's all there. Thanks very much!
