### ISSUE TITLE
Can't view dotnet image from Microsoft

### ISSUE THREAD

**Issue by SuperSandro2000** [microscaling/microbadger#64]
I can't view dotnet images from Microsoft like ``mcr.microsoft.com/dotnet/core/runtime:2.2-alpine`` or ``mcr.microsoft.com/dotnet/core/sdk:2.2-alpine`` cause the site thinks I want to access a subdirectory.

**Comment by lizrice** [comment]
Right now we only support images from Docker Hub

**Comment by SuperSandro2000** [comment]
So they host this image https://hub.docker.com/_/microsoft-dotnet-core-runtime/ on azure or what?
