### ISSUE TITLE
Official Debian images are not fetched anymore

### ISSUE THREAD

**Issue by erikmd** [microscaling/microbadger#65]
Hello,

The `buster` version of [Debian](https://hub.docker.com/_/debian/) has recently been [released](https://www.debian.org/News/2019/20190706) (on July 6th) as Debian 10, 
however Microbadger does not provide metadata for any recent image since [buster-20190610](https://microbadger.com/images/debian:buster-20190610).

Namely, the three following tags raise the message `not found`:
- https://microbadger.com/images/debian:10
- https://microbadger.com/images/debian:buster-20190812
- https://microbadger.com/images/debian:buster-20190708

Could you take a look at this issue?

**Comment by erikmd** [comment]
Closing this issue, which is now fixed :+1:

**Comment by simon-bueler** [comment]
It seem, that it this happened again so since buster-20191014 there has been no update.
