### ISSUE TITLE
Stop sending unsolicited emails regarding badges

### ISSUE THREAD

**Issue by andyvanee** [microscaling/microbadger#8]
After uploading a container Github & Docker Hub I received an unsolicited email from Anne Currie <anne@microscaling.com> regarding a badge for my image. I've marked the email as spam, as there was no unsubscribe options given. Please stop doing this.

**Comment by aecurrie** [comment]
Hi Andy, So sorry we annoyed you! We are trying to only send 1 email to folk we see are active container builders to see if they are interested in metadata and labelling. Was it your 1andyvanee@gmail.com email address I need to add to our do not send spreadsheet?

Many apologies,
Anne

**Comment by andyvanee** [comment]
Hi Anne, I'm actually not too concerned about my own email address, but I thought your product looked interesting enough to let you know that this may be hurting your brand. Your privacy policy states that emails from you should have an unsubscribe button. <http://microscaling.com/privacy.html>

In most of the world this is somewhat rude, but here in Canada, this type of email is actually illegal according to CASL (Canadian Anti-Spam Legislation), since it does not meet the following criteria:

1. Emails from companies must be opt-in, not included by default with any other sign up.
2. Must have a clear unsubscribe mechanism.

<http://www2.deloitte.com/ca/en/pages/risk/articles/canada-anti-spam-law-casl-faq.html>

Thanks :)

**Comment by aecurrie** [comment]
Hi Andy,

It's an interesting point. I should absolutely update the email with a line saying reply to unsubscribe (we've only had 3 other unsubscribers and they just mailed me but I haven't put that in explicitly. I will do so now!). And I'll read through the CASL. It's an interesting one as we don't actually have a mailing list - we only plan to mail folk once. The reception has been really positive generally (we weren't sure if people would be annoyed so we don't send out many and only to folk who are quite active) and we keep it small enough that I can chat to everyone who has any questions or ideas. Some folk have excellent ideas :-)

Thanks!
Anne

**Comment by andyvanee** [comment]
Okay, thanks!

**Comment by mr-c** [comment]
Yeah, this is super rude even if "only once". Please don't.
